/*****************************************************/
/*****************************************************/
/******** Author      : Mahmoud Elbadrawy    *********/
/******** Layer       : MCAL                 *********/
/******** Component   : DIO_Configuration    *********/
/******** version     : 1.0 V                *********/
/******** Date        : 24/4/2023            *********/
/*****************************************************/
/*****************************************************/

/* file guard, the file will be called one time in .c      */
#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*Direction of PORTA*/
/*Option (DIO_PIN_OUTPUT / DIO_PIN_INPUT)*/
#define DIO_PORTA_PIN0_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN1_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN2_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN3_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN4_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN5_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN6_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTA_PIN7_INIT_DIR		DIO_PIN_OUTPUT

/*Direction of PORTB*/
/*Option (DIO_PIN_OUTPUT / DIO_PIN_INPUT)*/
#define DIO_PORTB_PIN0_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN1_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN2_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN3_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN4_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN5_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN6_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTB_PIN7_INIT_DIR		DIO_PIN_OUTPUT

/*Direction of PORTC*/
/*Option (DIO_PIN_OUTPUT / DIO_PIN_INPUT)*/
#define DIO_PORTC_PIN0_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN1_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN2_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN3_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN4_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN5_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN6_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTC_PIN7_INIT_DIR		DIO_PIN_OUTPUT

/*Direction of PORTD*/
/*Option (DIO_PIN_OUTPUT / DIO_PIN_INPUT)*/
#define DIO_PORTD_PIN0_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN1_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN2_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN3_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN4_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN5_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN6_INIT_DIR		DIO_PIN_OUTPUT
#define DIO_PORTD_PIN7_INIT_DIR		DIO_PIN_OUTPUT


/*Value of PORTA*/
/*Options (DIO_PIN_HIGH / DIO_PIN_LOW)*/
#define DIO_PORTA_PIN0_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN1_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN2_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN3_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN4_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN5_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN6_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTA_PIN7_INIT_VAL		DIO_PIN_LOW

/*Value of PORTB*/
/*Options (DIO_PIN_HIGH / DIO_PIN_LOW)*/
#define DIO_PORTB_PIN0_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN1_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN2_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN3_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN4_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN5_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN6_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTB_PIN7_INIT_VAL		DIO_PIN_LOW

/*Value of PORTC*/
/*Options (DIO_PIN_HIGH / DIO_PIN_LOW)*/
#define DIO_PORTC_PIN0_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN1_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN2_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN3_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN4_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN5_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN6_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTC_PIN7_INIT_VAL		DIO_PIN_LOW

/*value of PORTD*/
/*Options (DIO_PIN_HIGH / DIO_PIN_LOW)*/
#define DIO_PORTD_PIN0_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN1_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN2_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN3_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN4_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN5_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN6_INIT_VAL		DIO_PIN_LOW
#define DIO_PORTD_PIN7_INIT_VAL		DIO_PIN_LOW



#endif /* MCAL_DIO_DIO_CONFIG_H_ */


